# 확률은 최대 소수점 3자리
# ex) 0.005, 10.775

# itemsAdder 플러그인으로 생성한 커스텀 블록 이용은
# CUSTOM_name 형식으로 작성. ex) CUSTOM_NEW_BLOCK
# 단, CUSTOM 블록 사용을 위해선, config.yml 에서 USE_ITEMS_ADDER 항목을 true 로 설정

OAK_FENCE:
  STONE: 70
  OAK_WOOD: 30

DARK_OAK_FENCE:
  STONE: 50
  DIAMOND_ORE: 50
